In [ ]:
#problem1 a
# this code is used to generate a trajectory using monte carlo or probability emthod
# with 2 trajectory storage capacity
# we first generate a random movement and check if the movement is legal by checking
# if it hits the wall or obstacle
# if it pass the test, we execute it by changing state variable

import random

width=10
length=10

def insidewindow(x,y):
    if x<width and x>=0:
        if y<length and y>=0:
            return True
    else:
        return False
def obstacle(x,y):
    if x==0 and y==3: 
        return False # hitting the obstacle 
    elif x==1 and y==3:
        return False
    elif x==2 and y==3:
        return False
    elif x==3 and y==3:
        return False
    elif x==4 and y==3:
        return False
    elif x==7 and y==3:
        return False
    elif x==8 and y==3:
        return False
    elif x==9 and y==3:
        return False
    else:
        return True

prev_trajectory= [0,0,0,0,0,0,0,0,0,0,0, \
                0,0,0,0,0,0,0,0,0,0,0,\
                     0,0,0,0,0,0,0,0,0,0,0,\
                     0,0,0,0,0,0,0,0,0,0,0,\
                     0,0,0,0,0,0,0,0,0,0,0,\
                     0,0,0,0,0,0,0,0,0,0,0,\
                     0,0,0,0,0,0,0,0,0,0,0,\
                     0,0,0,0,0,0,0,0,0,0,0,\
                     0,0,0,0,0,0,0,0,0,0,0,\
                     0,0,0,0,0,0,0,0,0,0,0]

current_trajectory= [0,0,0,0,0,0,0,0,0,0,0, \
                0,0,0,0,0,0,0,0,0,0,0,\
                     0,0,0,0,0,0,0,0,0,0,0,\
                     0,0,0,0,0,0,0,0,0,0,0,\
                     0,0,0,0,0,0,0,0,0,0,0,\
                     0,0,0,0,0,0,0,0,0,0,0,\
                     0,0,0,0,0,0,0,0,0,0,0,\
                     0,0,0,0,0,0,0,0,0,0,0,\
                     0,0,0,0,0,0,0,0,0,0,0,\
                     0,0,0,0,0,0,0,0,0,0,0]

PI= [0.6,0.2,0.2] #probability of moving up, moving right, and moving left

count_move=0  # counting of legal move
count_move_prev=100 # record of best move minimal no of move
for k in range(1000):
    state_x=0
    state_y=0
    count_move=0
    for l in range(100):
            current_trajectory[l]=0 #make all item to zero
    for i in range(100):  # the number 100 need to be fixed maximal number of trials
        p=random.uniform(0,1) #generate another random number
        if p>=0 and p<=PI[0]:
            state_y=state_y+1  # MOVE UP
            if insidewindow(state_x,state_y) and obstacle(state_x,state_y):
                current_trajectory[count_move]= 1
                count_move=count_move+1
            else:
                state_y=state_y-1
               
        elif p>PI[0] and p<=(PI[0]+PI[1]):
            state_x=state_x+1 #move right
            if insidewindow(state_x,state_y)and obstacle(state_x,state_y):
                current_trajectory[count_move]= 2
                count_move=count_move+1
            else:
                state_x=state_x-1
        else:
            state_x=state_x-1 #move left
            if insidewindow(state_x,state_y)and obstacle(state_x,state_y):
                current_trajectory[count_move]= 3
                count_move=count_move+1
            else:
                state_x=state_x+1
        #goal checking 
        if state_x==width-1 and state_y==length-1:
            # unmask the following line to check if goal is reached
            #print('iteration',k, 'move', count_move, 'goal reached')
            break
    if count_move<count_move_prev: #if the current move is better
        count_move_prev=count_move
        for j in range(100):
            prev_trajectory[j]=current_trajectory[j] #store the move history
    if k % 100==0:  #sampling result of improvement when 10000 iteration used change 100 to 1000
        
        print('iter', k, 'result', count_move_prev)
        
for i in range(100):
    if prev_trajectory[i] !=0:
        
        print('index', i, 'movement', prev_trajectory[i])        


iter 0 result 38
iter 100 result 18
iter 200 result 18
iter 300 result 18
iter 400 result 18
iter 500 result 18
iter 600 result 18
iter 700 result 18
iter 800 result 18
iter 900 result 18
index 0 movement 1
index 1 movement 1
index 2 movement 2
index 3 movement 2
index 4 movement 2
index 5 movement 2
index 6 movement 2
index 7 movement 1
index 8 movement 1
index 9 movement 1
index 10 movement 1
index 11 movement 2
index 12 movement 2
index 13 movement 2
index 14 movement 1
index 15 movement 2
index 16 movement 1
index 17 movement 1


In [ ]:
#problem1 b
# this code is used to generate a trajectory using monte carlo or probability emthod
# with 2 trajectory storage capacity
# we first generate a random movement and check if the movement is legal by checking
# if it hits the wall or obstacle
# if it pass the test, we execute it by changing state variable

import random

width=10
length=10

def insidewindow(x,y):
    if x<width and x>=0:
        if y<length and y>=0:
            return True
    else:
        return False
def obstacle(x,y):
    if x==5 and y==0: 
        return False # hitting the obstacle 
    elif x==5 and y==1:
        return False
    elif x==5 and y==2:
        return False
    elif x==5 and y==3:
        return False
    elif x==5 and y==6:
        return False
    elif x==5 and y==7:
        return False
    elif x==5 and y==8:
        return False
    elif x==5 and y==9:
        return False
    else:
        return True
prev_trajectory= [0,0,0,0,0,0,0,0,0,0,0, \
                0,0,0,0,0,0,0,0,0,0,0,\
                     0,0,0,0,0,0,0,0,0,0,0,\
                     0,0,0,0,0,0,0,0,0,0,0,\
                     0,0,0,0,0,0,0,0,0,0,0,\
                     0,0,0,0,0,0,0,0,0,0,0,\
                     0,0,0,0,0,0,0,0,0,0,0,\
                     0,0,0,0,0,0,0,0,0,0,0,\
                     0,0,0,0,0,0,0,0,0,0,0,\
                     0,0,0,0,0,0,0,0,0,0,0]

current_trajectory= [0,0,0,0,0,0,0,0,0,0,0, \
                0,0,0,0,0,0,0,0,0,0,0,\
                     0,0,0,0,0,0,0,0,0,0,0,\
                     0,0,0,0,0,0,0,0,0,0,0,\
                     0,0,0,0,0,0,0,0,0,0,0,\
                     0,0,0,0,0,0,0,0,0,0,0,\
                     0,0,0,0,0,0,0,0,0,0,0,\
                     0,0,0,0,0,0,0,0,0,0,0,\
                     0,0,0,0,0,0,0,0,0,0,0,\
                     0,0,0,0,0,0,0,0,0,0,0]

PI= [0.6,0.2,0.2] #probability of moving up, moving right, and moving left

count_move=0  # counting of legal move
count_move_prev=100 # record of best move minimal no of move
for k in range(1000):
    state_x=0
    state_y=0
    count_move=0
    for l in range(100):
            current_trajectory[l]=0 #make all item to zero
    for i in range(100):  # the number 100 need to be fixed maximal number of trials
        p=random.uniform(0,1) #generate another random number
        if p>=0 and p<=PI[0]:
            state_y=state_y+1  # MOVE UP
            if insidewindow(state_x,state_y) and obstacle(state_x,state_y):
                current_trajectory[count_move]= 1
                count_move=count_move+1
            else:
                state_y=state_y-1
               
        elif p>PI[0] and p<=(PI[0]+PI[1]):
            state_x=state_x+1 #move right
            if insidewindow(state_x,state_y)and obstacle(state_x,state_y):
                current_trajectory[count_move]= 2
                count_move=count_move+1
            else:
                state_x=state_x-1
        else:
            state_y=state_y-1 #move down
            if insidewindow(state_x,state_y)and obstacle(state_x,state_y):
                current_trajectory[count_move]= 3
                count_move=count_move+1
            else:
                state_y=state_y+1
        #goal checking 
        if state_x==9 and state_y==0:
            # unmask the following line to check if goal is reached
            print('iteration',k, 'move', count_move, 'goal reached')
            break
    if count_move<count_move_prev: #if the current move is better
        count_move_prev=count_move
        for j in range(100):
            prev_trajectory[j]=current_trajectory[j] #store the move history
    if k % 100==0:  #sampling result of improvement when 10000 iteration used change 100 to 1000
        
        print('iter', k, 'result', count_move_prev)
        
for i in range(100):
    if prev_trajectory[i] !=0:
        
        print('index', i, 'movement', prev_trajectory[i])

iter 0 result 59
iter 100 result 31
iter 200 result 31
iter 300 result 31
iter 400 result 31
iteration 455 move 33 goal reached
iteration 478 move 29 goal reached
iter 500 result 29
iter 600 result 29
iter 700 result 29
iteration 753 move 59 goal reached
iter 800 result 29
iter 900 result 29
index 0 movement 1
index 1 movement 3
index 2 movement 2
index 3 movement 2
index 4 movement 1
index 5 movement 3
index 6 movement 1
index 7 movement 3
index 8 movement 2
index 9 movement 1
index 10 movement 3
index 11 movement 1
index 12 movement 2
index 13 movement 1
index 14 movement 1
index 15 movement 1
index 16 movement 2
index 17 movement 1
index 18 movement 3
index 19 movement 1
index 20 movement 2
index 21 movement 2
index 22 movement 2
index 23 movement 2
index 24 movement 3
index 25 movement 3
index 26 movement 3
index 27 movement 3
index 28 movement 3


In [ ]:
#problem 2
# Commented out IPython magic to ensure Python compatibility.
# Python ≥3.5 is required
import sys
assert sys.version_info >= (3, 5)


# Scikit-Learn ≥0.20 is required
import sklearn
assert sklearn.__version__ >= "0.20"

# TensorFlow ≥2.0 is required
import tensorflow as tf
from tensorflow import keras
assert tf.__version__ >= "2.0"



# Common imports
import numpy as np
import os

# to make this notebook's output stable across runs
np.random.seed(42)
tf.random.set_seed(42)

# To plot pretty figures
# %matplotlib inline
import matplotlib as mpl
import matplotlib.pyplot as plt
mpl.rc('axes', labelsize=14)
mpl.rc('xtick', labelsize=12)
mpl.rc('ytick', labelsize=12)

np.random.seed(42)

transition_probabilities = [ # shape=[s, s']
        [0.7, 0.2, 0.0, 0.1],  # from s0 to s0, s1, s2, s3
        [0.0, 1.0, 0.0, 0.0],  # from s1 to ...
        [0.0, 0.9, 0.0, 0.1],  # from s2 to ...
        [0.8, 0.2, 0.0, 0.0]]  # from s3 to ...

n_max_steps = 50

def print_sequence():
    current_state = 0
    print("States:", end=" ")
    for step in range(n_max_steps):
        print(current_state, end=" ")
        # unmask the following and change the 3 to the expected terminal state
        if current_state == 3:
            break
        current_state = np.random.choice(range(4), p=transition_probabilities[current_state])
    else:
        print("...", end="")
    print()

for _ in range(10):
    print_sequence()


States: 0 0 3 
States: 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 ...
States: 0 3 
States: 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 ...
States: 0 0 3 
States: 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 ...
States: 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 ...
States: 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 ...
States: 0 0 3 
States: 0 0 0 0 0 3 


In [ ]:
#Problem 3 a
# Commented out IPython magic to ensure Python compatibility.
# Python ≥3.5 is required
import sys
assert sys.version_info >= (3, 5)


# Scikit-Learn ≥0.20 is required
import sklearn
assert sklearn.__version__ >= "0.20"

# TensorFlow ≥2.0 is required
import tensorflow as tf
from tensorflow import keras
assert tf.__version__ >= "2.0"



# Common imports
import numpy as np
import os

# to make this notebook's output stable across runs
np.random.seed(42)
tf.random.set_seed(42)

# To plot pretty figures
# %matplotlib inline
import matplotlib as mpl
import matplotlib.pyplot as plt
mpl.rc('axes', labelsize=14)
mpl.rc('xtick', labelsize=12)
mpl.rc('ytick', labelsize=12)

np.random.seed(42)


# markov decision process 
transition_probabilities = [ # shape=[s, a, s']
        [[0.7, 0.3, 0.0], [1.0, 0.0, 0.0], [0.8, 0.2, 0.0]],
        [[0.0, 1.0, 0.0], None, [0.0, 0.0, 1.0]],
        [None, [0.8, 0.1, 0.1], None]]
rewards = [ # shape=[s, a, s']
        [[+10, 0, 0], [0, 0, 0], [0, 0, 0]],
        [[0, 0, 0], [0, 0, 0], [0, 0, +50]],
        [[0, 0, 0], [+40, 0, 0], [0, 0, 0]]]
possible_actions = [[0, 1, 2], [0, 2], [1]]

Q_values = np.full((3, 3), -np.inf) # -np.inf for impossible actions
for state, actions in enumerate(possible_actions):
    Q_values[state, actions] = 0.0  # for all possible actions

gamma = 0.9  # the discount factor

history1 = [] # Not shown in the book (for the figure below)
for iteration in range(50):
    Q_prev = Q_values.copy()
    history1.append(Q_prev) # Not shown
    for s in range(3):
        for a in possible_actions[s]:
            Q_values[s, a] = np.sum([
                    transition_probabilities[s][a][sp]
                    * (rewards[s][a][sp] + gamma * np.max(Q_prev[sp]))
                for sp in range(3)])

history1 = np.array(history1) # Not shown
Q_values
#np.argmax(Q_values, axis=1)
# it is best to check Q_values and then optimal policy
#The optimal policy for this MDP, when using a discount factor of 0.90, 
#is to choose action a0 when in state s0, and choose action a0 when in state s1,
# and finally choose action a1 (the only possible action) when in state s2.


array([[195.20173993, 175.57359999, 183.99235995],
       [217.66739979,         -inf, 241.9726286 ],
       [        -inf, 213.42288283,         -inf]])

In [ ]:
#Problem 3 b
# Commented out IPython magic to ensure Python compatibility.
# Python ≥3.5 is required
import sys
assert sys.version_info >= (3, 5)


# Scikit-Learn ≥0.20 is required
import sklearn
assert sklearn.__version__ >= "0.20"

# TensorFlow ≥2.0 is required
import tensorflow as tf
from tensorflow import keras
assert tf.__version__ >= "2.0"



# Common imports
import numpy as np
import os

# to make this notebook's output stable across runs
np.random.seed(42)
tf.random.set_seed(42)

# To plot pretty figures
# %matplotlib inline
import matplotlib as mpl
import matplotlib.pyplot as plt
mpl.rc('axes', labelsize=14)
mpl.rc('xtick', labelsize=12)
mpl.rc('ytick', labelsize=12)

np.random.seed(42)


# markov decision process 
transition_probabilities = [ # shape=[s, a, s']
        [[0.7, 0.3, 0.0], [1.0, 0.0, 0.0], [0.8, 0.2, 0.0]],
        [[0.0, 1.0, 0.0], None, [0.0, 0.0, 1.0]],
        [None, [0.8, 0.1, 0.1], None]]
rewards = [ # shape=[s, a, s']
        [[+10, +40, 0], [0, 0, 0], [0, 0, 0]],
        [[0, 0, 0], [0, 0, 0], [0, 0, -50]],
        [[0, 0, 0], [+40, 0, 0], [0, 0, 0]]]
possible_actions = [[0, 1, 2], [0, 2], [1]]

Q_values = np.full((3, 3), -np.inf) # -np.inf for impossible actions
for state, actions in enumerate(possible_actions):
    Q_values[state, actions] = 0.0  # for all possible actions

gamma = 0.9  # the discount factor

history1 = [] # Not shown in the book (for the figure below)
for iteration in range(50):
    Q_prev = Q_values.copy()
    history1.append(Q_prev) # Not shown
    for s in range(3):
        for a in possible_actions[s]:
            Q_values[s, a] = np.sum([
                    transition_probabilities[s][a][sp]
                    * (rewards[s][a][sp] + gamma * np.max(Q_prev[sp]))
                for sp in range(3)])

history1 = np.array(history1) # Not shown
Q_values
#np.argmax(Q_values, axis=1)
# it is best to check Q_values and then optimal policy
#The optimal policy for this MDP, when using a discount factor of 0.90, 
#is to choose action a0 when in state s0, and choose action a0 when in state s1,
# and finally choose action a1 (the only possible action) when in state s2.

array([[ 84.98201404,  76.45048182,  69.4715033 ],
       [ 41.55558921,         -inf,  46.20991113],
       [        -inf, 106.93693549,         -inf]])

In [ ]:
#Problem 3 c
# Commented out IPython magic to ensure Python compatibility.
# Python ≥3.5 is required
import sys
assert sys.version_info >= (3, 5)


# Scikit-Learn ≥0.20 is required
import sklearn
assert sklearn.__version__ >= "0.20"

# TensorFlow ≥2.0 is required
import tensorflow as tf
from tensorflow import keras
assert tf.__version__ >= "2.0"



# Common imports
import numpy as np
import os

# to make this notebook's output stable across runs
np.random.seed(42)
tf.random.set_seed(42)

# To plot pretty figures
# %matplotlib inline
import matplotlib as mpl
import matplotlib.pyplot as plt
mpl.rc('axes', labelsize=14)
mpl.rc('xtick', labelsize=12)
mpl.rc('ytick', labelsize=12)

np.random.seed(42)


# markov decision process 
transition_probabilities = [ # shape=[s, a, s']
        [[0.7, 0.3, 0.0], [1.0, 0.0, 0.0], [0.8, 0.2, 0.0]],
        [[0.0, 1.0, 0.0], None, [0.0, 0.0, 1.0]],
        [None, [0.8, 0.1, 0.1], None]]
rewards = [ # shape=[s, a, s']
        [[+10, 0, 0], [0, 0, 0], [0, 0, 0]],
        [[0, 0, 0], [0, 0, 0], [0, 0, -50]],
        [[0, 0, 0], [+40, 0, 0], [0, 0, 0]]]
possible_actions = [[0, 1, 2], [0, 2], [1]]

Q_values = np.full((3, 3), -np.inf) # -np.inf for impossible actions
for state, actions in enumerate(possible_actions):
    Q_values[state, actions] = 0.0  # for all possible actions

gamma = 0.8  # the discount factor

history1 = [] # Not shown in the book (for the figure below)
for iteration in range(50):
    Q_prev = Q_values.copy()
    history1.append(Q_prev) # Not shown
    for s in range(3):
        for a in possible_actions[s]:
            Q_values[s, a] = np.sum([
                    transition_probabilities[s][a][sp]
                    * (rewards[s][a][sp] + gamma * np.max(Q_prev[sp]))
                for sp in range(3)])

history1 = np.array(history1) # Not shown
Q_values
#np.argmax(Q_values, axis=1)
# it is best to check Q_values and then optimal policy
#The optimal policy for this MDP, when using a discount factor of 0.90, 
#is to choose action a0 when in state s0, and choose action a0 when in state s1,
# and finally choose action a1 (the only possible action) when in state s2.


array([[ 15.90909091,  12.72727273,  10.18181818],
       [  0.        ,         -inf, -13.3201581 ],
       [        -inf,  45.84980237,         -inf]])

In [ ]:
#Problem 3 c
# Commented out IPython magic to ensure Python compatibility.
# Python ≥3.5 is required
import sys
assert sys.version_info >= (3, 5)


# Scikit-Learn ≥0.20 is required
import sklearn
assert sklearn.__version__ >= "0.20"

# TensorFlow ≥2.0 is required
import tensorflow as tf
from tensorflow import keras
assert tf.__version__ >= "2.0"



# Common imports
import numpy as np
import os

# to make this notebook's output stable across runs
np.random.seed(42)
tf.random.set_seed(42)

# To plot pretty figures
# %matplotlib inline
import matplotlib as mpl
import matplotlib.pyplot as plt
mpl.rc('axes', labelsize=14)
mpl.rc('xtick', labelsize=12)
mpl.rc('ytick', labelsize=12)

np.random.seed(42)


# markov decision process 
transition_probabilities = [ # shape=[s, a, s']
        [[0.7, 0.3, 0.0], [1.0, 0.0, 0.0], [0.8, 0.2, 0.0]],
        [[0.0, 1.0, 0.0], None, [0.0, 0.0, 1.0]],
        [None, [0.8, 0.1, 0.1], None]]
rewards = [ # shape=[s, a, s']
        [[+10, 0, 0], [0, 0, 0], [0, 0, 0]],
        [[0, 0, 0], [0, 0, 0], [0, 0, -50]],
        [[0, 0, 0], [+40, 0, 0], [0, 0, 0]]]
possible_actions = [[0, 1, 2], [0, 2], [1]]

Q_values = np.full((3, 3), -np.inf) # -np.inf for impossible actions
for state, actions in enumerate(possible_actions):
    Q_values[state, actions] = 0.0  # for all possible actions

gamma = 0.95  # the discount factor

history1 = [] # Not shown in the book (for the figure below)
for iteration in range(50):
    Q_prev = Q_values.copy()
    history1.append(Q_prev) # Not shown
    for s in range(3):
        for a in possible_actions[s]:
            Q_values[s, a] = np.sum([
                    transition_probabilities[s][a][sp]
                    * (rewards[s][a][sp] + gamma * np.max(Q_prev[sp]))
                for sp in range(3)])

history1 = np.array(history1) # Not shown
Q_values
#np.argmax(Q_values, axis=1)
# it is best to check Q_values and then optimal policy
#The optimal policy for this MDP, when using a discount factor of 0.90, 
#is to choose action a0 when in state s0, and choose action a0 when in state s1,
# and finally choose action a1 (the only possible action) when in state s2.


array([[21.73304188, 20.63807938, 16.70138772],
       [ 0.95462106,        -inf,  1.01361207],
       [       -inf, 53.70728682,        -inf]])

In [1]:
# Commented out IPython magic to ensure Python compatibility.
# Python ≥3.5 is required
import sys
assert sys.version_info >= (3, 5)


# Scikit-Learn ≥0.20 is required
import sklearn
assert sklearn.__version__ >= "0.20"

# TensorFlow ≥2.0 is required
import tensorflow as tf
from tensorflow import keras
assert tf.__version__ >= "2.0"



# Common imports
import numpy as np
import os

# to make this notebook's output stable across runs
np.random.seed(42)
tf.random.set_seed(42)

# To plot pretty figures
# %matplotlib inline
import matplotlib as mpl
import matplotlib.pyplot as plt
mpl.rc('axes', labelsize=14)
mpl.rc('xtick', labelsize=12)
mpl.rc('ytick', labelsize=12)

np.random.seed(42)


# markov decision process 
transition_probabilities = [ # shape=[s, a, s']
        [[0.7, 0.3, 0.0], [1.0, 0.0, 0.0], [0.8, 0.2, 0.0]],
        [[0.0, 1.0, 0.0], None, [0.0, 0.0, 1.0]],
        [None, [0.8, 0.1, 0.1], None]]
rewards = [ # shape=[s, a, s']
        [[+10, 0, 0], [0, 0, 0], [0, 0, 0]],
        [[0, 0, 0], [0, 0, 0], [0, 0, -50]],
        [[0, 0, 0], [+40, 0, 0], [0, 0, 0]]]
possible_actions = [[0, 1, 2], [0, 2], [1]]

Q_values = np.full((3, 3), -np.inf) # -np.inf for impossible actions
for state, actions in enumerate(possible_actions):
    Q_values[state, actions] = 0.0  # for all possible actions

gamma = 0.90  # the discount factor

history1 = [] # Not shown in the book (for the figure below)
for iteration in range(50):
    Q_prev = Q_values.copy()
    history1.append(Q_prev) # Not shown
    for s in range(3):
        for a in possible_actions[s]:
            Q_values[s, a] = np.sum([
                    transition_probabilities[s][a][sp]
                    * (rewards[s][a][sp] + gamma * np.max(Q_prev[sp]))
                for sp in range(3)])

history1 = np.array(history1) # Not shown
Q_values
#np.argmax(Q_values, axis=1)
# it is best to check Q_values and then optimal policy
#The optimal policy for this MDP, when using a discount factor of 0.90, 
#is to choose action a0 when in state s0, and choose action a0 when in state s1,
# and finally choose action a1 (the only possible action) when in state s2.

#Q learning 
#We will need to simulate an agent moving around in the environment, 
#so let's define a function to perform some action and get the new state 
#and a reward:
def step(state, action):
    probas = transition_probabilities[state][action]
    next_state = np.random.choice([0, 1, 2], p=probas)
    reward = rewards[state][action][next_state]
    return next_state, reward
#We also need an exploration policy. We will just use a random policy, 
# since the state space is very small:
def exploration_policy(state):
    return np.random.choice(possible_actions[state])

np.random.seed(42)

Q_values = np.full((3, 3), -np.inf)
for state, actions in enumerate(possible_actions):
    Q_values[state][actions] = 0

alpha0 = 0.05 # initial learning rate
decay = 0.005 # learning rate decay
gamma = 0.90 # discount factor
state = 0 # initial state
history2 = [] # Not shown 

for iteration in range(10000):
    history2.append(Q_values.copy()) # Not shown
    action = exploration_policy(state)
    next_state, reward = step(state, action)
    next_value = np.max(Q_values[next_state]) # greedy policy at the next step
    alpha = alpha0 / (1 + iteration * decay)
    Q_values[state, action] *= 1 - alpha
    Q_values[state, action] += alpha * (reward + gamma * next_value)
    state = next_state

history2 = np.array(history2) # Not shown
Q_values

array([[18.77621289, 17.2238872 , 13.74543343],
       [ 0.        ,        -inf, -8.00485647],
       [       -inf, 49.40208921,        -inf]])